# The node ID, peer ID/address map (empty for single node), and log level.
id: 1
peers: {}
log_level: INFO

# Network addresses to bind the SQL and Raft servers to.
listen_sql: 0.0.0.0:9605
listen_raft: 0.0.0.0:9705

# Node data directory, and the garbage fraction threshold at which to trigger
# database compaction when opening the database (Bitcask only).
data_dir: data
compact_threshold: 0.2

# Raft log storage engine
# - bitcask (default): an append-only log-structured store.
# - memory: an in-memory store using the Rust standard library's BTreeMap.
storage_raft: bitcask

# SQL key-value storage engine
# - bitcask (default): an append-only log-structured store.
# - memory: an in-memory store using the Rust standard library's BTreeMap.
storage_sql: bitcask
